create or replace view v_htx_order_rcd as
select o.num,
       decode(o.optype, 10, 'in', 20, 'out',30, 'stock',40, 'back') optypeurl,
       g.*,
       decode(o.opstat,
              10,
              '辅材',
              20,
              '原料',
              30,
              '半成品',
              40,
              '委托物资',
              50,
              '成品') OpStatText,
       decode(g.optype,
              10,
              '入库',
              15,
              '出库',
              70,
              '库存调整',
              75,
              '成本调整',
              80,
              '退货',
              20,
              '原料入库单',
              30,
              '半成品入库单',
              40,
              '委托发料',
              45,
              '委托收料',
              16,
              '退货',
              17,
              '加工损耗',
              21,
              '移库',
              17,
              '加工损耗',
              18,
              '在库损耗') OpTypeText
  from htx_order o, htx_order_rcd g
 where o.entgid = g.entgid
   and o.gid = g.gid
 order by g.opdate, g.opgdcode;
